
version: '3.9'

networks:
  aimx-network:
    driver: bridge

services:
  ex-identity:
    image: nagagogulan/aimx-identity:latest
    container_name: identity-container
    ports:
      - "8081:8081"
    environment:
      - DBHOST=13.229.196.7
      - DBPORT=5432
      - DBUSER=myappuser
      - DBPASSWORD=SmartWork@123
      - DBNAME=aimxdb
      - MONGO_URI=mongodb://13.229.196.7:27017
      - MONGO_DBNAME=mydb
      - KAFKA_URL=13.229.196.7:9092
      - SMTP_EMAIL=nithiyavel402@gmail.com
      - ACCESS_SECRET=UQnP5Uv3SxZjeO7Dn5kK3Fx9WoqVUuX1N6OApUpkT4I=
      - REFRESH_SECRET=kC3aYdRHfYJtzEZ0Rh8JrD8PIl1hKDHAlNYNoBMcB0o=
      - ACCESS_EXPIRE_MINUTES=15
      - REFRESH_EXPIRE_HOURS=168
    networks:
      - aimx-network

  forms:
    image: nagagogulan/aimx-forms:latest
    container_name: forms-container
    ports:
      - "8082:8082"
    environment:
      - DBHOST=13.229.196.7
      - DBPORT=5432
      - DBUSER=myappuser
      - DBPASSWORD=SmartWork@123
      - DBNAME=aimxdb
      - MONGO_URI=mongodb://13.229.196.7:27017
      - MONGO_DBNAME=mydb
      - KAFKA_URL=13.229.196.7:9092
      - SMTP_EMAIL=nithiyavel402@gmail.com
      - ACCESS_SECRET=UQnP5Uv3SxZjeO7Dn5kK3Fx9WoqVUuX1N6OApUpkT4I=
      - REFRESH_SECRET=kC3aYdRHfYJtzEZ0Rh8JrD8PIl1hKDHAlNYNoBMcB0o=
      - ACCESS_EXPIRE_MINUTES=15
      - REFRESH_EXPIRE_HOURS=168
    networks:
      - aimx-network

  roles:
    image: nagagogulan/aimx-roles:latest
    container_name: roles-container
    ports:
      - "8083:8083"
    environment:
      - DBHOST=13.229.196.7
      - DBPORT=5432
      - DBUSER=myappuser
      - DBPASSWORD=SmartWork@123
      - DBNAME=aimxdb
      - MONGO_URI=mongodb://13.229.196.7:27017
      - MONGO_DBNAME=mydb
      - KAFKA_URL=13.229.196.7:9092
      - SMTP_EMAIL=nithiyavel402@gmail.com
      - ACCESS_SECRET=UQnP5Uv3SxZjeO7Dn5kK3Fx9WoqVUuX1N6OApUpkT4I=
      - REFRESH_SECRET=kC3aYdRHfYJtzEZ0Rh8JrD8PIl1hKDHAlNYNoBMcB0o=
      - ACCESS_EXPIRE_MINUTES=15
      - REFRESH_EXPIRE_HOURS=168
    networks:
      - aimx-network

  dataset:
    image: nagagogulan/aimx-dataset:latest
    container_name: dataset-container
    ports:
      - "8084:8084"
    environment:
      - DBHOST=13.229.196.7
      - DBPORT=5432
      - DBUSER=myappuser
      - DBPASSWORD=SmartWork@123
      - DBNAME=aimxdb
      - MONGO_URI=mongodb://13.229.196.7:27017
      - MONGO_DBNAME=mydb
      - KAFKA_URL=13.229.196.7:9092
      - SMTP_EMAIL=nithiyavel402@gmail.com
      - ACCESS_SECRET=UQnP5Uv3SxZjeO7Dn5kK3Fx9WoqVUuX1N6OApUpkT4I=
      - REFRESH_SECRET=kC3aYdRHfYJtzEZ0Rh8JrD8PIl1hKDHAlNYNoBMcB0o=
      - ACCESS_EXPIRE_MINUTES=15
      - REFRESH_EXPIRE_HOURS=168
    networks:
      - aimx-network

  profile:
    image: nagagogulan/aimx-profile:latest
    container_name: profile-container
    ports:
      - "8085:8085"
    environment:
      - DBHOST=13.229.196.7
      - DBPORT=5432
      - DBUSER=myappuser
      - DBPASSWORD=SmartWork@123
      - DBNAME=aimxdb
      - MONGO_URI=mongodb://13.229.196.7:27017
      - MONGO_DBNAME=mydb
      - KAFKA_URL=13.229.196.7:9092
      - SMTP_EMAIL=nithiyavel402@gmail.com
      - ACCESS_SECRET=UQnP5Uv3SxZjeO7Dn5kK3Fx9WoqVUuX1N6OApUpkT4I=
      - REFRESH_SECRET=kC3aYdRHfYJtzEZ0Rh8JrD8PIl1hKDHAlNYNoBMcB0o=
      - ACCESS_EXPIRE_MINUTES=15
      - REFRESH_EXPIRE_HOURS=168
    networks:
      - aimx-network

  user_management:
    image: nagagogulan/aimx-user-management:latest
    container_name: user-management-container
    ports:
      - "8086:8086"
    environment:
      - DBHOST=13.229.196.7
      - DBPORT=5432
      - DBUSER=myappuser
      - DBPASSWORD=SmartWork@123
      - DBNAME=aimxdb
      - MONGO_URI=mongodb://13.229.196.7:27017
      - MONGO_DBNAME=mydb
      - KAFKA_URL=13.229.196.7:9092
      - SMTP_EMAIL=nithiyavel402@gmail.com
      - ACCESS_SECRET=UQnP5Uv3SxZjeO7Dn5kK3Fx9WoqVUuX1N6OApUpkT4I=
      - REFRESH_SECRET=kC3aYdRHfYJtzEZ0Rh8JrD8PIl1hKDHAlNYNoBMcB0o=
      - ACCESS_EXPIRE_MINUTES=15
      - REFRESH_EXPIRE_HOURS=168
    networks:
      - aimx-network
