version: '3.9'

networks:
  aimx-network:
    driver: bridge

services:
  int-identity:
    build:
      context: ./applications/identity
      dockerfile: Dockerfile
    container_name: identity-container
    ports:
      - "8081:8081"
    environment:
      - DBHOST=${INT_DBHOST}
      - DBPORT=${INT_DBPORT}
      - DBUSER=${INT_DBUSER}
      - DBPASSWORD=${INT_DBPASSWORD}
      - DBNAME=${INT_DBNAME}
      - MONGO_URI=${INT_MONGO_URI}
      - MONGO_DBNAME=${INT_MONGO_DBNAME}
      - KAFKA_URL=${INT_KAFKA_URL}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PAS=${SMTP_PAS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
      - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
    env_file:
      - .env
    networks:
      - aimx-network

  # int-forms:
  #   build:
  #     context: ./applications/forms
  #     dockerfile: Dockerfile
  #   container_name: forms-container
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - DBHOST=${INT_DBHOST}
  #     - DBPORT=${INT_DBPORT}
  #     - DBUSER=${INT_DBUSER}
  #     - DBPASSWORD=${INT_DBPASSWORD}
  #     - DBNAME=${INT_DBNAME}
  #     - MONGO_URI=${INT_MONGO_URI}
  #     - MONGO_DBNAME=${INT_MONGO_DBNAME}
  #     - KAFKA_URL=${INT_KAFKA_URL}
  #     - SMTP_EMAIL=${SMTP_EMAIL}
  #     - SMTP_PAS=${SMTP_PAS}
  #     - ACCESS_SECRET=${ACCESS_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #     - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
  #     - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
  #   env_file:
  #     - .env
  #   networks:
  #     - aimx-network

  # int-roles:
  #   build:
  #     context: ./applications/roles
  #     dockerfile: Dockerfile
  #   container_name: roles-container
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - DBHOST=${INT_DBHOST}
  #     - DBPORT=${INT_DBPORT}
  #     - DBUSER=${INT_DBUSER}
  #     - DBPASSWORD=${INT_DBPASSWORD}
  #     - DBNAME=${INT_DBNAME}
  #     - MONGO_URI=${INT_MONGO_URI}
  #     - MONGO_DBNAME=${INT_MONGO_DBNAME}
  #     - KAFKA_URL=${INT_KAFKA_URL}
  #     - SMTP_EMAIL=${SMTP_EMAIL}
  #     - SMTP_PAS=${SMTP_PAS}
  #     - ACCESS_SECRET=${ACCESS_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #     - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
  #     - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
  #   env_file:
  #     - .env
  #   networks:
  #     - aimx-network

  int-dataset:
    build:
      context: ./applications/dataset
      dockerfile: Dockerfile
    container_name: dataset-container
    ports:
      - "8084:8084"
    environment:
      - DBHOST=${INT_DBHOST}
      - DBPORT=${INT_DBPORT}
      - DBUSER=${INT_DBUSER}
      - DBPASSWORD=${INT_DBPASSWORD}
      - DBNAME=${INT_DBNAME}
      - MONGO_URI=${INT_MONGO_URI}
      - MONGO_DBNAME=${INT_MONGO_DBNAME}
      - KAFKA_URL=${INT_KAFKA_URL}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PAS=${SMTP_PAS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
      - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
    env_file:
      - .env
    networks:
      - aimx-network


  int-profile:
    build:
      context: ./applications/profile
      dockerfile: Dockerfile
    container_name: profile-container
    ports:
      - "8085:8085"
    environment:
      - DBHOST=${INT_DBHOST}
      - DBPORT=${INT_DBPORT}
      - DBUSER=${INT_DBUSER}
      - DBPASSWORD=${INT_DBPASSWORD}
      - DBNAME=${INT_DBNAME}
      - MONGO_URI=${INT_MONGO_URI}
      - MONGO_DBNAME=${INT_MONGO_DBNAME}
      - KAFKA_URL=${INT_KAFKA_URL}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PAS=${SMTP_PAS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
      - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
    env_file:
      - .env
    networks:
      - aimx-network    

  # int-user_management:
  #   build:
  #     context: ./applications/user_management
  #     dockerfile: Dockerfile
  #   container_name: user-management-container
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - DBHOST=${INT_DBHOST}
  #     - DBPORT=${INT_DBPORT}
  #     - DBUSER=${INT_DBUSER}
  #     - DBPASSWORD=${INT_DBPASSWORD}
  #     - DBNAME=${INT_DBNAME}
  #     - MONGO_URI=${INT_MONGO_URI}
  #     - MONGO_DBNAME=${INT_MONGO_DBNAME}
  #     - KAFKA_URL=${INT_KAFKA_URL}
  #     - SMTP_EMAIL=${SMTP_EMAIL}
  #     - SMTP_PAS=${SMTP_PAS}
  #     - ACCESS_SECRET=${ACCESS_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #     - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
  #     - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
  #   env_file:
  #     - .env
  #   networks:
  #     - aimx-network


  # int-request_management:
  #   build:
  #     context: ./applications/request_management
  #     dockerfile: Dockerfile
  #   container_name: request-management-container
  #   ports:
  #     - "8087:8087"
  #   environment:
  #     - DBHOST=${INT_DBHOST}
  #     - DBPORT=${INT_DBPORT}
  #     - DBUSER=${INT_DBUSER}
  #     - DBPASSWORD=${INT_DBPASSWORD}
  #     - DBNAME=${INT_DBNAME}
  #     - MONGO_URI=${INT_MONGO_URI}
  #     - MONGO_DBNAME=${INT_MONGO_DBNAME}
  #     - KAFKA_URL=${INT_KAFKA_URL}
  #     - SMTP_EMAIL=${SMTP_EMAIL}
  #     - SMTP_PAS=${SMTP_PAS}
  #     - ACCESS_SECRET=${ACCESS_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #     - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
  #     - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
  #   env_file:
  #     - .env
  #   networks:
  #     - aimx-network

  # int-external-kafka:
  #   build:
  #     context: ./applications/external-kafka
  #     dockerfile: Dockerfile
  #   container_name: external-kafka-container
  #   ports:
  #     - "8088:8088"
  #   environment:
  #     - DBHOST=${EXT_DBHOST}
  #     - DBPORT=${EXT_DBPORT}
  #     - DBUSER=${EXT_DBUSER}
  #     - DBPASSWORD=${EXT_DBPASSWORD}
  #     - DBNAME=${EXT_DBNAME}
  #     - MONGO_URI=${EXT_MONGO_URI}
  #     - MONGO_DBNAME=${EXT_MONGO_DBNAME}
  #     - KAFKA_BROKER_ADDRESS=${EXT_KAFKA_URL}
  #     - SMTP_EMAIL=${SMTP_EMAIL}
  #     - SMTP_PAS=${SMTP_PAS}
  #     - ACCESS_SECRET=${ACCESS_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #     - ACCESS_EXPIRE_MINUTES=${ACCESS_EXPIRE_MINUTES}
  #     - REFRESH_EXPIRE_HOURS=${REFRESH_EXPIRE_HOURS}
       
  #   env_file:
  #     - .env
  #   networks:
  #     - aimx-network